greenery:
  target: dbt_greenery_bigquery
  outputs:
    dbt_greenery_bigquery:
      type: bigquery
      method: service-account
      project: dataengineer-bootcamp
      dataset: dbt_greenery
      threads: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: asia-southeast1
